name: Actividad DAW
on: workflow_dispatch
jobs:
    test:
       runs-on: ubuntu-latest
       steps:
          - 
            name: Copiar código
            uses: actions/checkout@v4
          - 
            name:  Ejecutar requerimientos
            run: pip install -r requirements.txt
          - 
            name: Ejecutart tests
            run: pytest
    buildear-imagen-docker:
      runs-on: ubuntu-latest
      steps:
       -
        name: Checkout
        uses: actions/checkout@v4
       - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: fruizotero/calculadora-back-daw:latest
    



